//Team 4
// Author Brittany Hooley (assisted by Jessica Smither)

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HarryPotter;

import java.util.Arrays;
import java.lang.String;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;

//import Quiz;
/**
 *
 * @author jessicasmither
 */
public class HP_GUI extends javax.swing.JFrame {

    Quiz qz = new Quiz(9);
    Question qt = new Question();
    static int qCounter = -1;
    JLabel jLabel2;
    
    /**
     * Creates new form HP_GUI
     */
    public HP_GUI() {
        initComponents();
//        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("src/main/java/Resources/Images/HatBackGroundLarger.png"));
//        jLabel2.setIcon(icon);
//        jLabel2.setText("jLabel2");
//        jLabel2.setBounds(new java.awt.Rectangle(0, 0, 900, 506));
//        jLabel2.setMaximumSize(new java.awt.Dimension(900, 506));
//        jLabel2.setMinimumSize(new java.awt.Dimension(900, 506));
//        jLabel2.setPreferredSize(new java.awt.Dimension(900, 506));
//        getContentPane().add(jLabel2);
//        jLabel2.setBounds(0, 0, 900, 506);
        
        qz.readQuestion("questions.txt", "gAnswers.txt", "hAnswers.txt", "rAnswers.txt", "sAnswers.txt");
//        qz.readQuestion(
//                "/Users/jessicasmither/Desktop/questions.txt",
//                "/Users/jessicasmither/Desktop/gAnswers.txt", 
//                "/Users/jessicasmither/Desktop/hAnswers.txt", 
//                "/Users/jessicasmither/Desktop/rAnswers.txt", 
//                "/Users/jessicasmither/Desktop/sAnswers.txt");
        jLabel1.setText("Welcome to the Sorting Hat Quiz!");
        jButton5.setText("Start Quiz");
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        //qz.display();
        //qz.score();
        //update();
    }
    
    /**
     *
     */
    public void update(){
        if(qCounter < qz.numberOfQs - 1){
            qCounter++;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jLabel1.setText(qz.questions[qCounter].text);
            //System.out.println(qz.questions[qCounter].randomizedAnswers()[0]);
            jButton1.setText(qz.questions[qCounter].randomizedAnswers()[0]);
            jButton2.setText(qz.questions[qCounter].randomizedAnswers()[1]);
            jButton3.setText(qz.questions[qCounter].randomizedAnswers()[2]);
            jButton4.setText(qz.questions[qCounter].randomizedAnswers()[3]);
            jButton5.setVisible(false);
            
        }
        else
        {
            qz.getScoreResult();
            jLabel1.setText(qz.scoreResult);
            //jLabel1.setLocation(400, 300);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setText("Exit Quiz");
            jButton5.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HP_Quiz");
        setMinimumSize(new java.awt.Dimension(900, 506));
        setSize(new java.awt.Dimension(900, 506));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Question");
        jLabel1.setName("Question"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 526, 82);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("Answer1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 120, 421, 29);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setText("Answer2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 160, 421, 29);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setText("Answer3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 200, 421, 29);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton4.setText("Answer4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 240, 421, 29);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton5.setText("Start/Exit");
        jButton5.setLocation(new java.awt.Point(396, 340));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 340, 109, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        qz.updateScore(1, qCounter);
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        qz.updateScore(2, qCounter);
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        qz.updateScore(3, qCounter);
        update();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        qz.updateScore(4, qCounter);
        update();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jButton5.getText() == "Exit Quiz"){
            System.exit(0);
        }else{
            update();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HP_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HP_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
